### ISSUE TITLE
Controls Assessement Spec v 7.1 Still Available

### ISSUE THREAD

**Issue by maxima2k** [CISecurity/ControlsAssessmentSpecification#17]
Sorry if this is the wrong place to ask.  But not sure where to ask.  Is the assessment spec v 7.1 still available?  Not ready to move to v8 quite yet.

**Comment by wmunyan** [comment]
@maxima2k if you navigate to https://controls-assessment-specification.readthedocs.io/en/1.0.0/ you can find CAS v7.1

**Comment by maxima2k** [comment]
Perfect, thanks.
